-- Add an ID column as a primary key
DROP TABLE member IF EXISTS;

CREATE TABLE member
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY, -- This line adds the ID
    name VARCHAR(255),
    PRIMARY KEY (id)
);